import 'reflect-metadata';
import 'dotenv/config';

import express, { Request, Response, NextFunction } from 'express';
import cors from 'cors';
import { errors } from 'celebrate';
import 'express-async-errors';

// No arquivo package.json:
// A dependÃªncia 'ts-node-dev' faz papel do nodemon e tambÃ©m do typescript
// O comando '--ignore-watch node_modules' serve para ignorar possÃ­veis alteraÃ§Ãµes na node_modules a
// nÃ­vel de cÃ³digo
// O comando '--transpileOnly' serve apenas para converter o cÃ³digo de ts para js sem se preocupar
// com erros, o vscode cuida disso
// A flag '--inspect' serve para o debug do vscode se conectar Ã  aplicaÃ§Ã£o
import uploadConfig from '@config/upload';
import AppError from '@shared/errors/AppError';
import rateLimiter from './middlewares/rateLimiter';
import routes from './routes';

import '@shared/infra/typeorm';
import '@shared/container';

const app = express();

app.use(cors());
app.use(express.json());
app.use('/files', express.static(uploadConfig.uploadsFolder));
app.use(rateLimiter);
app.use(routes);

app.use(errors());

/**
 * Este Ãºltimo app (que Ã© um middleware de erros) precisa vir depois das rotas,
 * pois ele irÃ¡ tratar dos erros das rotas. O 'if' serve para tratar dos erros
 * conhecidos/esperados, o console.err Ã© para rastrear o erro e o return vem com
 * um erro nÃ£o esperado. E para os erros cairem aqui neste middleware Ã© necessÃ¡rio
 * addicionar um pacote chamado express-async-errors, pois sem ele o node nÃ£o trata
 * os errors sem o try/catch que foram removidos dos cÃ³digos de rotas
 */

/**
 * Aqui onde tem o "_" como variÃ¡vel de recebimento da function (que era para ser um "next"),
 * o es-lint dava erro de minhoquinha, mas foi colocado a regra "@typescript-eslint/no-unused-vars"...
 * para que o es-lint nÃ£o ficasse reclamando
 */
app.use((err: Error, request: Request, response: Response, _: NextFunction) => {
  if (err instanceof AppError) {
    return response.status(err.statusCode).json({
      status: 'error',
      message: err.message,
    });
  }

  console.error(err);

  return response.status(500).json({
    status: 'error',
    message: 'Internal server error',
  });
});

app.listen(3333, () => {
  console.log('ğŸš€ Server started on port 3333!');
});
